name: opened

on: 
  pull_request:
    branches:
    - main
    types:
    - opened

jobs:
  releases_pr_opened:
    if:  startsWith(github.head_ref, 'releases/')    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: bundle
      run: npm run bundle

    - name: npm TEST
      run: npm version patch